from collections import deque
import pytest

from app.setgame import Card, Color, Number, Shading, Shape

@pytest.fixture
def standard_deck():
    cards = [
        Card(
            shape=Shape.OVAL,
            shading=Shading.SOLID,
            number=Number.THREE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.EMPTY,
            number=Number.ONE,
            color=Color.RED,
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.EMPTY,
            number=Number.THREE,
            color=Color.RED,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.STRIPED,
            number=Number.TWO,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.SOLID,
            number=Number.TWO,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.SOLID,
            number=Number.TWO,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.SOLID,
            number=Number.ONE,
            color=Color.RED,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.EMPTY,
            number=Number.ONE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.EMPTY,
            number=Number.TWO,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.SOLID,
            number=Number.ONE,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.SOLID,
            number=Number.THREE,
            color=Color.RED,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.SOLID,
            number=Number.ONE,
            color=Color.RED,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.EMPTY,
            number=Number.ONE,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.STRIPED,
            number=Number.TWO,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.STRIPED,
            number=Number.TWO,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.STRIPED,
            number=Number.THREE,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.EMPTY,
            number=Number.THREE,
            color=Color.RED,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.STRIPED,
            number=Number.TWO,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.OVAL, shading=Shading.EMPTY, number=Number.ONE, color=Color.BLUE
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.EMPTY,
            number=Number.THREE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.SOLID,
            number=Number.TWO,
            color=Color.RED,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.STRIPED,
            number=Number.THREE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.SOLID,
            number=Number.THREE,
            color=Color.RED,
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.STRIPED,
            number=Number.ONE,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.SOLID,
            number=Number.THREE,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.EMPTY,
            number=Number.THREE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.EMPTY,
            number=Number.TWO,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.SOLID,
            number=Number.THREE,
            color=Color.RED,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.EMPTY,
            number=Number.TWO,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.SOLID,
            number=Number.THREE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.SOLID,
            number=Number.THREE,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.EMPTY,
            number=Number.ONE,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.SOLID,
            number=Number.TWO,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.STRIPED,
            number=Number.THREE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.SOLID,
            number=Number.THREE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.OVAL, shading=Shading.SOLID, number=Number.TWO, color=Color.BLUE
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.STRIPED,
            number=Number.ONE,
            color=Color.RED,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.EMPTY,
            number=Number.TWO,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.EMPTY,
            number=Number.THREE,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.OVAL, shading=Shading.SOLID, number=Number.TWO, color=Color.RED
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.STRIPED,
            number=Number.THREE,
            color=Color.RED,
        ),
        Card(
            shape=Shape.OVAL, shading=Shading.SOLID, number=Number.ONE, color=Color.BLUE
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.STRIPED,
            number=Number.ONE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.SOLID,
            number=Number.ONE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.EMPTY,
            number=Number.TWO,
            color=Color.RED,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.STRIPED,
            number=Number.ONE,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.EMPTY,
            number=Number.THREE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.STRIPED,
            number=Number.ONE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.EMPTY,
            number=Number.TWO,
            color=Color.RED,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.STRIPED,
            number=Number.ONE,
            color=Color.RED,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.EMPTY,
            number=Number.ONE,
            color=Color.RED,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.SOLID,
            number=Number.THREE,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.STRIPED,
            number=Number.ONE,
            color=Color.RED,
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.STRIPED,
            number=Number.THREE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.STRIPED,
            number=Number.TWO,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.STRIPED,
            number=Number.THREE,
            color=Color.RED,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.EMPTY,
            number=Number.THREE,
            color=Color.RED,
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.EMPTY,
            number=Number.ONE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.STRIPED,
            number=Number.TWO,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.STRIPED,
            number=Number.TWO,
            color=Color.RED,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.EMPTY,
            number=Number.ONE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.SOLID,
            number=Number.TWO,
            color=Color.RED,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.EMPTY,
            number=Number.THREE,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.OVAL, shading=Shading.EMPTY, number=Number.TWO, color=Color.RED
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.SOLID,
            number=Number.ONE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.SOLID,
            number=Number.TWO,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.STRIPED,
            number=Number.ONE,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.SOLID,
            number=Number.ONE,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.STRIPED,
            number=Number.ONE,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.EMPTY,
            number=Number.THREE,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.STRIPED,
            number=Number.TWO,
            color=Color.RED,
        ),
        Card(
            shape=Shape.OVAL, shading=Shading.EMPTY, number=Number.ONE, color=Color.RED
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.EMPTY,
            number=Number.TWO,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.STRIPED,
            number=Number.THREE,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.OVAL, shading=Shading.EMPTY, number=Number.TWO, color=Color.BLUE
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.STRIPED,
            number=Number.TWO,
            color=Color.RED,
        ),
        Card(
            shape=Shape.OVAL,
            shading=Shading.SOLID,
            number=Number.TWO,
            color=Color.GREEN,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.STRIPED,
            number=Number.THREE,
            color=Color.RED,
        ),
        Card(
            shape=Shape.DIAMOND,
            shading=Shading.STRIPED,
            number=Number.THREE,
            color=Color.BLUE,
        ),
        Card(
            shape=Shape.OVAL, shading=Shading.SOLID, number=Number.ONE, color=Color.RED
        ),
        Card(
            shape=Shape.SQUIGGLE,
            shading=Shading.SOLID,
            number=Number.ONE,
            color=Color.GREEN,
        ),
    ]
    return deque(cards)


@pytest.fixture
def larger_deck():
    cards = [
        Card(
            shading=Shading.EMPTY, shape=Shape.OVAL, color=Color.RED, number=Number.ONE
        ),
        Card(
            shading=Shading.EMPTY, shape=Shape.OVAL, color=Color.BLUE, number=Number.ONE
        ),
        Card(
            shading=Shading.EMPTY, shape=Shape.OVAL, color=Color.BLUE, number=Number.TWO
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.DIAMOND,
            color=Color.RED,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.EMPTY, shape=Shape.OVAL, color=Color.RED, number=Number.TWO
        ),
        Card(
            shading=Shading.SOLID, shape=Shape.OVAL, color=Color.RED, number=Number.ONE
        ),
        Card(
            shading=Shading.SOLID, shape=Shape.OVAL, color=Color.BLUE, number=Number.TWO
        ),
        Card(
            shading=Shading.SOLID, shape=Shape.OVAL, color=Color.RED, number=Number.TWO
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.DIAMOND,
            color=Color.BLUE,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.DIAMOND,
            color=Color.RED,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.DIAMOND,
            color=Color.BLUE,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.DIAMOND,
            color=Color.RED,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.DIAMOND,
            color=Color.BLUE,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.DIAMOND,
            color=Color.BLUE,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.DIAMOND,
            color=Color.RED,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.SOLID, shape=Shape.OVAL, color=Color.BLUE, number=Number.ONE
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.DIAMOND,
            color=Color.GREEN,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.SQUIGGLE,
            color=Color.RED,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.SQUIGGLE,
            color=Color.BLUE,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.DIAMOND,
            color=Color.BLUE,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.OVAL,
            color=Color.RED,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.SQUIGGLE,
            color=Color.RED,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.OVAL,
            color=Color.BLUE,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.OVAL,
            color=Color.BLUE,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.SQUIGGLE,
            color=Color.RED,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.SQUIGGLE,
            color=Color.RED,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.SQUIGGLE,
            color=Color.BLUE,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.SQUIGGLE,
            color=Color.GREEN,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.OVAL,
            color=Color.RED,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.SQUIGGLE,
            color=Color.BLUE,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.OVAL,
            color=Color.GREEN,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.SQUIGGLE,
            color=Color.GREEN,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.OVAL,
            color=Color.BLUE,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.DIAMOND,
            color=Color.BLUE,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.DIAMOND,
            color=Color.GREEN,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.OVAL,
            color=Color.GREEN,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.OVAL,
            color=Color.RED,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.SQUIGGLE,
            color=Color.RED,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.DIAMOND,
            color=Color.GREEN,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.SQUIGGLE,
            color=Color.BLUE,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.SQUIGGLE,
            color=Color.GREEN,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.OVAL,
            color=Color.RED,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.OVAL,
            color=Color.GREEN,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.OVAL,
            color=Color.GREEN,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.DIAMOND,
            color=Color.GREEN,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.OVAL,
            color=Color.BLUE,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.DIAMOND,
            color=Color.GREEN,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.OVAL,
            color=Color.BLUE,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.OVAL,
            color=Color.RED,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.DIAMOND,
            color=Color.GREEN,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.DIAMOND,
            color=Color.GREEN,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.OVAL,
            color=Color.GREEN,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.DIAMOND,
            color=Color.GREEN,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.SQUIGGLE,
            color=Color.GREEN,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.SQUIGGLE,
            color=Color.GREEN,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.SQUIGGLE,
            color=Color.BLUE,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.DIAMOND,
            color=Color.RED,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.OVAL,
            color=Color.GREEN,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.OVAL,
            color=Color.GREEN,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.SQUIGGLE,
            color=Color.RED,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.DIAMOND,
            color=Color.BLUE,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.DIAMOND,
            color=Color.RED,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.SQUIGGLE,
            color=Color.BLUE,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.SQUIGGLE,
            color=Color.GREEN,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.SQUIGGLE,
            color=Color.RED,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.DIAMOND,
            color=Color.RED,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.DIAMOND,
            color=Color.RED,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.DIAMOND,
            color=Color.RED,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.SQUIGGLE,
            color=Color.GREEN,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.SQUIGGLE,
            color=Color.BLUE,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.SQUIGGLE,
            color=Color.GREEN,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.DIAMOND,
            color=Color.BLUE,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.OVAL,
            color=Color.GREEN,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.SQUIGGLE,
            color=Color.BLUE,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.SQUIGGLE,
            color=Color.BLUE,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.DIAMOND,
            color=Color.BLUE,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.DIAMOND,
            color=Color.GREEN,
            number=Number.TWO,
        ),
        Card(
            shading=Shading.SOLID,
            shape=Shape.SQUIGGLE,
            color=Color.GREEN,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.OVAL,
            color=Color.GREEN,
            number=Number.ONE,
        ),
        Card(
            shading=Shading.EMPTY,
            shape=Shape.SQUIGGLE,
            color=Color.RED,
            number=Number.THREE,
        ),
        Card(
            shading=Shading.STRIPED,
            shape=Shape.SQUIGGLE,
            color=Color.RED,
            number=Number.THREE,
        ),
    ]
    return deque(cards)